run:
  timeout: 5m
issues:
  exclude-dirs:
    - frontend
    - node_modules
    - dist
linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unused
    - gofmt
    - revive
    - gocyclo
    - gosec
